name: Rust

# on: [push]
on:
  push:
    paths: ["src/**/*.rs"] # event filtering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
